### ISSUE TITLE
Some minor feedback since you asked on twitter :)

### ISSUE THREAD

**Issue by bergquist** [patriksvensson/gocalc#1]
Use the flag package for getting cmd args
https://golang.org/pkg/flag/

https://github.com/patriksvensson/gocalc/blob/master/parser/parser.go#L9
avoid using make for creating empty slices 
https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

https://github.com/patriksvensson/gocalc/blob/master/parser/tokenizer.go#L29
Use `fmt.ErrorF` instead

https://github.com/patriksvensson/gocalc/blob/117ca8cf68202973190efdd0a83ee665f258aa93/parser/evaluator.go#L18
Avoid using `new` for creating empty structs. Use `&elevator{}` instead.

tests? :)

**Comment by patriksvensson** [comment]
@bergquist Thanks for your feedback! I really appreciate it since I don't write any Go code in my day job (yet).

Tests is on the agenda (I'm normally a big proponent of testing). Need to get to the tests chapter in the book first though 😄

**Comment by bergquist** [comment]
TDD in golang can be a bit frustrating compared to c# since the compiler complains about used vars,  imports etc. But eventually, you get used to it :)
